Jvm Spawn
jacobtonder/flix pull request #86
Opened 2018-05-17 12:45 UTC by emilbaekdahl

2018-05-17 12:52 UTC, jespersandnielsen submitted a review, later dismissed

2018-05-17 12:52 UTC, Sansemand commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
> +      visitor.visitMethodInsn(INVOKESPECIAL, JvmName.Thread.toInternalName, "<init>", AsmOps.getMethodDescriptor(List(JvmType.Runnable), JvmType.Void), false)
Add name for thread

2018-05-17 12:52 UTC, Sansemand commented on main/src/ca/uwaterloo/flix/language/phase/jvm/RunnableSpawn.java
> +
Remove this file

2018-05-17 12:52 UTC, Sansemand commented on main/src/ca/uwaterloo/flix/runtime/interpreter/Interpreter.scala
> +import scala.collection.mutable.ListBuffer
Remove this import - we don't use it anymore

2018-05-17 12:52 UTC, Sansemand commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenExpression.scala
> +      visitor.visitVarInsn(ASTORE, 1)
Dont use `ASTORE` use the stack instead

2018-05-21 09:50 UTC, jacobtonder requested changes

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenClosureClasses.scala
> +
Remove newline

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +    //genToString(visitor)
Remove

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +    //genEquals(visitor)
Remove

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +  }
new line

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +    initMethod.visitFieldInsn(PUTFIELD, JvmName.RunnableSpawn.toInternalName, "fn", functionType.toDescriptor)
New line

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +      AsmOps.getMethodDescriptor(List(JvmType.Context), JvmType.Void), true)
new line

2018-05-21 09:50 UTC, jacobtonder commented on main/src/ca/uwaterloo/flix/language/phase/jvm/GenRunnableSpawn.scala
> +    initMethod.visitVarInsn(ALOAD, 0)
Load these when needed, instead of loading them all at the same time.

2018-05-21 10:16 UTC, jacobtonder approved these changes

2018-05-21 10:18 UTC, merged